### ISSUE TITLE
Deprecated Link to AppAssure Documentation 

### ISSUE THREAD

**Issue by vnznznz** [rshipp/python-appassure#4]
The URL to the AppAssure documentation in autoImplementInterface.sh
 is deprecated. I've recently contacted Dell about the current docs and they sent them to me as an e-mail attachment. I don't know if I'm allowed to share it here. Maybe you can contact Dell about it.

**Comment by vnznznz** [comment]
I've talked to Dell and they'll put up-to-date documentation online in the next  days.

**Comment by rshipp** [comment]
Awesome, thanks. :cake:

**Comment by vnznznz** [comment]
Here are the Links:
- Core -> http://documents.software.dell.com/DOC308890
- Agent ->http://documents.software.dell.com/DOC308944

**Comment by rshipp** [comment]
Thanks. The format changed significantly on these, so `autoImplementInterface.sh` still won't work. You're welcome to fix it and send a PR if you like; I don't have time to work on something I don't need any more.

**Comment by vnznznz** [comment]
The .zip I've got from AppAssure-Support is better than the online docs. I would like to work on a PR but I currently don't have time. Maybe I'll get my employer to give me time for this :)

**Comment by vnznznz** [comment]
Got this from Dell: 
"There are no examples in these APIs. If customers really want them, we have 5.4.3.106 APIs for Core and Agent. You must mention that **_the APIs are specific to each release**_. You can send them the APIs as zipped HTML documents from the following links:

https://d3e0vf5fqy6y6q.cloudfront.net/Core.Contracts-5.4.3.106.zip and https://d3e0vf5fqy6y6q.cloudfront.net/Agent.Contracts-5.4.3.106.zip 

Updated APIs (distributed as HTML files) will be included in AppAssure 6.0.1 as part of an SDK, including examples, aimed for Q4 2015."
